### ISSUE TITLE
RFP-2 DERO Mining Pool to Support AstroBWT CPU Mining

### ISSUE THREAD

**Issue by Nelbert442** [deroproject/documentation#4]
# DERO Mining Pool to Support [AstroBWT CPU Mining](https://github.com/deroproject/astrobwt)

### DERO Golang Pool to be developed by Nelbert442 set out to accomplish the details and requirements set aside from https://github.com/deroproject/documentation/blob/master/proposals/RFP-2.md .

**Design Approach**
* Golang v1.13.6 will be leveraged for development and testing. If requirements for additional versions, this can be worked through no problem.
* In conjunction with existing mining pool [dero-pool](https://git.dero.io/Nelbert442/dero-pool) , I will be converting a vast majority of functionality to golang and remove the need for nodejs and other requirements.
* To accomplish this, during the process, I will be leveraging ~~redis~~ Graviton for backend storage and json for frontend/api surfacing
* README will feature configuration file commenting for ease-of-use as well as step-by-step instructions on going from 0 - 100 and getting the pool running.
* Any and all attempts to use built-in derosuite functions will be taken into account/consideration throughout the process, most importantly surrounding AstroBWT.
* RPC will be leveraged for querying local or remote daemons and wallets in order to accomplish proper work/job advertisement and payments.
* ALL DERO addresses will be taken into account, including: integrated (dERi/dETi), paymentID, normal (dERo/dETo), testnet & mainnet [based on 'pool' address in config].
* Every login will support and parse paymentID, workerID, fixedDifficulty and solo mining to provide more functionality to the miner.
* Initially PROP (proportional) pool scheme will be leveraged, but in future to be followed by PPLNS and potentially others, with the ability to switch through which scheme to leverage easily in the configuration file.
* Initially a simple web interface to track pool state and outcomes will be leveraged, however as a probable last step to get a more robust frontend up and running.
* End of the day, ease-of-use of the code will be important and tweaked over time. I will imagine that a few phases of development will occur in regards to this.

**Development Time**
* ~~Development is already underway, roughly 2 weeks in, and will expect full development time to be approximately 3 - 4 weeks or so.~~ Took approximately 6-8 weeks, development is ongoing for fixes/features etc.

**Estimated Fee (in DERO)**
* N/A

Repo for following development: https://github.com/Nelbert442/dero-golang-pool

**Comment by CaptainDero** [comment]
Thank you, Nelbert.
